export const DOOR_OPEN_REQUEST = 'DOOR_OPEN_REQUEST';
export const DOOR_OPEN_SUCCESS = 'DOOR_OPEN_SUCCESS';
export const DOOR_OPEN_FAIL = 'DOOR_OPEN_FAIL';
export const DOOR_CLOSE_REQUEST = 'DOOR_CLOSE_REQUEST';
export const DOOR_CLOSE_SUCCESS = 'DOOR_CLOSE_SUCCESS';
export const DOOR_CLOSE_FAIL = 'DOOR_CLOSE_FAIL';